name: SSH Setup

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenSSH Server
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          
      - name: Configure SSH User
        run: |
          # Replace 'your_username' with your desired SSH username.
          sudo useradd -m -s /bin/bash your_username
          sudo passwd your_username
          sudo usermod -aG sudo your_username
          
      - name: Display SSH Configuration
        run: |
          sudo systemctl status ssh
          sudo systemctl is-active ssh
          sudo systemctl is-enabled ssh
          
      - name: Set Up SSH Keys
        run: |
          # Generate an SSH key pair if you don't have one already.
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
          # Copy the public key to the authorized_keys file for the user.
          mkdir -p /home/your_username/.ssh
          cat ~/.ssh/id_rsa.pub > /home/your_username/.ssh/authorized_keys
          sudo chown -R your_username:your_username /home/your_username/.ssh
          
      - name: Show SSH Configuration
        run: |
          sudo cat /etc/ssh/sshd_config

